FROM docker.io/golang:1.24-alpine AS builder

WORKDIR /bethrou

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

WORKDIR /bethrou/client

RUN go build -trimpath -ldflags "-s -w" -o /out/bethrou ./

FROM docker.io/alpine:3.22

RUN apk add --no-cache ca-certificates

RUN mkdir -p /etc/bethrou

COPY --from=builder /out/bethrou /usr/bin/bethrou

EXPOSE 1080

VOLUME ["/etc/bethrou"]

ENTRYPOINT ["/usr/bin/bethrou", "connect", "--config", "/etc/bethrou/client.yaml", "--key", "/etc/bethrou/network.key"]
