FROM docker.io/golang:1.24-alpine AS builder

WORKDIR /bethrou

COPY go.mod .
COPY go.sum .

COPY node/go.mod node/go.mod
COPY node/go.sum node/go.sum

RUN go mod download

COPY . .

WORKDIR /bethrou/node

RUN go build -trimpath -ldflags "-s -w" -o /out/bethrou ./

FROM docker.io/alpine:3.22

RUN apk add --no-cache ca-certificates

RUN mkdir -p /etc/bethrou

COPY --from=builder /out/bethrou /usr/bin/bethrou

EXPOSE 4000

VOLUME ["/etc/bethrou"]

ENTRYPOINT ["/usr/bin/bethrou", "start", "--key", "/etc/bethrou/network.key"]
